---
title: "Juan Soriano in R"
author: "JG Pardyak"
date: "9/2/2022"
output: html_document
---

```{r setup2, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gganimate)
library(sf)
```

```{r}
devtools::install_github("JacekPardyak/inkscaper")
library(inkscaper)
```

```{r}
dir.create(file.path("Juan_Soriano/", "db"), showWarnings = FALSE)
#"Juan_Soriano/Retrato_de_Juan_Soriano_por_Mizael_C.svg" 
"https://upload.wikimedia.org/wikipedia/commons/c/c5/The_Photographer.svg" %>% 
  inx_actions(actions = "select-all;path-simplify", ext = ".svg") %>%
  inx_svg2sf() %>% select(geometry) %>%
  st_write("Juan_Soriano/db/Juan_Soriano.shp")

Zip_Files = list.files("Juan_Soriano/db", full.names = T)
zip(zipfile = "Juan_Soriano/db.zip", files = Zip_Files, flags = " a -tzip",
    zip = "C:\\Program Files\\7-Zip\\7Z")
unlink("Juan_Soriano/db", recursive=TRUE)
```

```{r}
df <- "https://upload.wikimedia.org/wikipedia/commons/c/c5/The_Photographer.svg" %>% 
  inx_actions(actions = "select-all;path-simplify", ext = ".svg") %>%
  inx_svg2sf() %>% select(geometry)

df %>% ggplot() +
  geom_sf() 
```

```{r}
df <- "https://upload.wikimedia.org/wikipedia/commons/c/c5/The_Photographer.svg" %>% 
  inx_actions(actions = "select-all;path-simplify", ext = ".svg") %>%
  inx_svg2sf() %>% select(geometry) %>% st_union() %>% st_polygonize()

df %>% ggplot() +
  geom_sf() 
```

```{r}
df_1 <- df_1 %>% st_union() %>% st_sfc() %>% st_sf() %>% mutate(facet = 1)
df_2 <- df_2 %>% st_union() %>% st_sfc() %>% st_sf() %>% mutate(facet = 2)
```


```{r}
res <- df_1 %>% bind_rows(df_2)
```



```{r}
library(gganimate)
res %>%
 ggplot() +
  geom_sf() +
  transition_states(
    facet,
    transition_length = 2,
    state_length = 1
  ) +
  enter_fade() + 
  exit_shrink() +
  ease_aes('sine-in-out')
```



```{r}
bbox <- st_bbox(df)
df_2 <- st_sfc() %>% st_sf()
for (i in c(1:nrow(df_1))) {
  tmp <- runif(2, bbox$xmin, bbox$xmax) %>% cbind(
runif(2, bbox$ymin, bbox$ymax)) %>% 
  st_linestring() %>% st_sfc() %>% st_sf()
  df_2 <- df_2 %>% bind_rows(tmp)
}

df_2 <- df_2
```








```{r}
res %>%
 ggplot() +
  geom_sf() +
  transition_states(facet)
```

