---
title: "Untitled"
output: html_document
---
  
```{r setup2, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(sf)
```  

```{r, setup}
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```

We start from checking Inkscape installation


```{r }
result <- st_read("./Red_Bird.shp")

result %>% ggplot() +
  geom_sf()
```


```{r}
grid_spacing = 1
grid <- result %>% st_make_grid(what = "centers", cellsize = c(grid_spacing, grid_spacing)) %>%
  st_sf() 
```

```{r}
heights <- st_join(grid, (result %>% select(geometry) %>% mutate(Z = 1))) %>% replace(is.na(.), 0) 
z <- heights %>% st_coordinates() %>% as_tibble() %>% 
  bind_cols(heights %>% st_drop_geometry()) %>%
  mutate(X = round(X,1)) %>%
  mutate(Y = round(Y,1)) %>% pivot_wider(names_from = Y, values_from = Z) %>%
  column_to_rownames("X") %>% as.matrix()
```

```{r, test-rgl, webgl=TRUE}
x <- 1:nrow(z)  
y <- 1:ncol(z)  

colorlut <- c("#F2F2F2",  "#E34234") #"#ECB176",
col <- colorlut[ z - min(z) + 1 ] # assign colors to heights for each point

#open3d()
surface3d(x, y, z, color = col, back = "lines")

#e34234
#close3d()
```

